### ISSUE TITLE
Running other tasks like Credo

### ISSUE THREAD

**Issue by Ch4s3** [influxdata/mix_test_interactive#52]
Is there any way to run things like Credo or Dialyxir from mix_test_interactive?

**Comment by randycoulman** [comment]
Not currently. mix_test_interactive is geared to manage the arguments being sent to `mix test`, so having it manage other tools doesn't make much sense.

[mix_test_watch](https://github.com/lpil/mix-test.watch) still supports that ability, though.

If you've got ideas on how to cleanly support other tools in a way that makes sense, we're totally open to the idea.

**Comment by Ch4s3** [comment]
You'd probably need a plugin system that can distinguish non-ex_unit stuff. I'll think on.
